### ISSUE TITLE
V0.1版电路原理图设计完成，欢迎伙伴们提意见和建议

### ISSUE THREAD

**Issue by sdlcnet** [fishros/fishbot-laser-control#3]
![Schematic V0 1](https://user-images.githubusercontent.com/3894983/158564456-adc2b98d-a71a-485a-b24e-4e2ddc324832.jpg)

**Comment by fishros** [comment]
哈喽，仔细看了下，有两点需要进行确认：
1. nodemcu上的usb和cp2102是否可以替换USBM(J2)和GP2102-GMR（U2）
2. A1雷达接口MOTOCTL（J4）接口需要确认是否会用到，如用到所需是信号类型也要确认

**Comment by sdlcnet** [comment]
> 哈喽，仔细看了下，有两点需要进行确认：
> 
> 1. nodemcu上的usb和cp2102是否可以替换USBM(J2)和GP2102-GMR（U2）
> 2. A1雷达接口MOTOCTL（J4）接口需要确认是否会用到，如用到所需是信号类型也要确认

Hi
  
  1. 可以使用nodemcu的usb端口和cp2102替代USBM(J2)和GP2102-GMR（U2）的功能，需要把SW2、SW3跳线连到2、3脚，并在nodemcu中写一个串口数据转发程序即可。这样做优点是可以省掉硬件部分的USBM(J2)和GP2102-GMR（U2）元件，缺点是对串口转发程序的转发实时性要求比较严格，尤其是在双向通讯且数据量较大时，可能会导致时序错误丢失数据情况。所以预留USBM(J2)和GP2102-GMR（U2）硬件转发方案，如果转发程序稳定可靠，可以不用焊接USBM(J2)和GP2102-GMR（U2）元件。
  
 2. 根据A1雷达使用手册说明，A1雷达接口MOTOCTL（J4）引脚需要连接5V(定速运转，最高速率)，或连接MCU PWM引脚(调速运转，只能降低速率)。具体使用中是否需要调速，我需要确认，我开一个issue确认此问题。这是一个好问题，确实是我的失误，忘记连接了。

**Comment by fishros** [comment]
@sdlcnet Hello
最近工作变动比较忙，没有回复，第一点我很认同，第二点正如issue中那样，我认为直接接入5V即可。

**Comment by sdlcnet** [comment]
@fishros 好的，一开始设计PCB。
