### ISSUE TITLE
A1雷达接口MOTOCTL调速问题

### ISSUE THREAD

**Issue by sdlcnet** [fishros/fishbot-laser-control#4]
hello 各位伙伴们好！

     根据A1雷达使用手册说明，A1雷达接口MOTOCTL 引脚需要连接5V(定速运转，最高速率)，或连接MCU PWM引脚(调速运转，只能降低速率)。具体使用中是否需要调速？

     如果需要降速运行，请说下，什么情况下需要降速运行。

   谢谢

**Comment by fishros** [comment]
看了下A1转接板的丝印标识，MOTOCTL引脚的是DTR（Data Terminal Ready），这个引脚应该上位机发指令交由CP2012进行控制，不知道这个想法对不对？

**Comment by sdlcnet** [comment]
转接板的DTR信号默认就是一个高电平输出。
如果不需要调速的话，MOTOCTL引脚接5V比较合适。
![image](https://user-images.githubusercontent.com/3894983/159645606-dc8fb513-771a-40e4-9c08-9088352e798a.png)

**Comment by fishros** [comment]
> 转接板的DTR信号默认就是一个高电平输出。 如果不需要调速的话，MOTOCTL引脚接5V比较合适。 ![image](https://user-images.githubusercontent.com/3894983/159645606-dc8fb513-771a-40e4-9c08-9088352e798a.png)

赞同直接接5V。
